data_file: '/home/student/akash/PeopleFlowDataset/ieee-bigdata-cup-2022-destination-prediction/train/train/Tokyo.csv'
feature_file: '/home/student/akash/PeopleFlowDataset/ieee-bigdata-cup-2022-destination-prediction/Zone_features/Zone_features/Tokyo_zone_feature_area.csv'
Trip_type: '2' # [ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 99]
filtered_file: '/home/student/akash/PeopleFlowDataset/Trip_Filtered_Data/filtered_df_${Trip_type}'



